### PR TITLE
i added a html and css file please have a look 

### PR DESCRIPTION
**Pull request by nitinbisht122003**
Screenshot (23)
Screenshot (21)
Screenshot (20)

### CODE REVIEW

**Comment by nitinbisht122003** [comment]
i want to  merge so please have a look

**Comment by nitinbisht122003** [comment]
Please have a look i have added all the css and html files.

**Review by rhvsingh — CHANGES_REQUESTED** [review]
What is round.html doing here?

**Comment by nitinbisht122003** [comment]
i remove it now have a look

**Review by rhvsingh — COMMENTED** [review]
Good work

**Pull request merged**
